version: '3.7'

services:
  apache:
    image: ${PROJECT_NAME}_apache
    container_name: ${PROJECT_NAME}_apache
    build:
      context: .
      dockerfile: docker/apache2.4/Dockerfile
      args:
        php_proxy_server: php_fpm:9000
    volumes:
      - ./src:/var/www/html
    depends_on:
      - php_fpm
    networks:
      - backend

  php_fpm:
    image: ${PROJECT_NAME}_php_fpm
    container_name: ${PROJECT_NAME}_php_fpm
    build:
      context: .
      dockerfile: docker/php7.4-fpm/Dockerfile
      args:
        environment: ${ENVIRONMENT}
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysqldb
    networks:
      - backend
      - db

  nginx:
    image: ${PROJECT_NAME}_nginx
    container_name: ${PROJECT_NAME}_nginx
    build:
      context: .
      dockerfile: docker/nginx1.17/Dockerfile
    ports:
      - ${WWW_PORT}:80
    volumes:
      - ./src:/var/www/html
    depends_on:
      - apache
    networks:
      - backend

  mysqldb:
    image: ${PROJECT_NAME}_mysql
    container_name: ${PROJECT_NAME}_mysql
    build:
      context: .
      dockerfile: docker/mysql8.0/Dockerfile
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER_NAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - mysqldb:/var/lib/mysql
    networks:
      - db

volumes:
  mysqldb:

networks:
  backend:
  db:
